### ISSUE TITLE
【git-provider】需要优化下针对 特定的错误码进行友好提示

### ISSUE THREAD

**Issue by heimanba** [serverless-cd/toolkit#121]
比如401 是不是直接提示无权限

**Comment by wss-git** [comment]
仅针对过期

**Comment by wss-git** [comment]
GitHub Api 针对返回码的说明：
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28#about-the-response-code-and-headers

Gitlib Api 针对返回码的说明：
https://www.bookstack.cn/read/gitlab-doc-zh/docs-284.md

gitee 没有找到针对这块做说明，但是中间有这样的一段描述
![image](https://user-images.githubusercontent.com/56686088/236607355-798027f2-eec1-4e63-b8d0-57d224923847.png)


综上， git-provider 接口应该都是遵循标准返回状态。再更具体的提示就需要深入到业务了，需要这样吗？
